services:
  - type: web
    name: grafana
    env: image
    plan: free
    image:
      url: grafana/grafana

  - type: web
    name: prometheus
    env: image
    plan: free
    image:
      url: prom/prometheus

  - type: web
    name: loki
    env: image
    plan: free
    image:
      url: grafana/loki:2.9.0

  - type: web
    name: tempo
    env: image
    plan: free
    image:
      url: grafana/tempo:2.3.0