services:
  - type: web
    name: grafana
<<<<<<< HEAD
    env: image
    plan: free
    image:
      url: grafana/grafana

  - type: web
    name: prometheus
    env: image
    plan: free
    image:
      url: prom/prometheus
=======
    env: docker
    plan: free
    dockerfilePath: ./services/grafana/Dockerfile

  - type: web
    name: prometheus
    env: docker
    plan: free
    dockerfilePath: ./services/prometheus/Dockerfile
>>>>>>> main

  - type: web
    name: loki
    env: image
    plan: free
    image:
      url: grafana/loki:2.9.0

  - type: web
    name: tempo
    env: docker
    plan: free
<<<<<<< HEAD
    dockerfilePath: ./services/tempo/Dockerfile
=======
    dockerfilePath: ./services/tempo/Dockerfile

  - type: web
    name: noor-backend
    env: docker
    plan: free
    dockerfilePath: ./services/backend/Dockerfile
    dockerContext: ./services/backend
    envVars:
      - key: PORT
        value: 4000
>>>>>>> main
