apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: https://prometheus-8etj.onrender.com
    access: proxy
    isDefault: true
    editable: false

  - name: Tempo
    type: tempo
    url: https://tempo-pzzd.onrender.com
    access: proxy
    editable: false

  - name: Loki
    type: loki
    url: https://loki-u6eg.onrender.com
    access: proxy
    editable: false
